services:
  master:
    build: .
    command: ./master/master 0 100 0.0000001 100000000
    depends_on:
      - worker1
      - worker2

  worker1:
    build: .
    command: ./worker/worker
  
  worker2:
    build: .
    command: ./worker/worker
