services:
  server1:
    build: .
    environment:
      MY_ID: 1
    ports:
      - "31337:31337"
    volumes:
      - "volume1:/main"
  
  server2:
    build: .
    environment:
      MY_ID: 2
    ports:
      - "31338:31338"
    volumes:
      - "volume2:/main"

  server3:
    build: .
    environment:
      MY_ID: 3
    ports:
      - "31339:31339"
    volumes:
      - "volume3:/main"

volumes:
  volume1:
  volume2:
  volume3:
