services:
  server1:
    build: .
    environment:
      MY_ID: 1
      API_HOST: "0.0.0.0"
      API_PORT: "31337"
    ports:
      - "10337:10337"
      - "31337:31337"
    volumes:
      - "volume1:/main"
  
  server2:
    build: .
    environment:
      MY_ID: 2
      API_HOST: "0.0.0.0"
      API_PORT: "31338"
    ports:
      - "10338:10338"
      - "31338:31338"
    volumes:
      - "volume2:/main"

  server3:
    build: .
    environment:
      MY_ID: 3
      API_HOST: "0.0.0.0"
      API_PORT: "31339"
    ports:
      - "10339:10339"
      - "31339:31339"
    volumes:
      - "volume3:/main"

volumes:
  volume1:
  volume2:
  volume3:
